services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_app
      POSTGRES_PASSWORD: Abishek@2004
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_app -d product_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: product_app
      DB_PASSWORD: Abishek@2004
      DB_NAME: product_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
