sonar.host.url=http://localhost:9000
sonar.projectKey=product-sales-management
sonar.projectName=product-sales-management
sonar.projectVersion=1.0

# Use sonar.login for SonarQube 9.x compatibility
sonar.login=sqp_cfe62e55125ae2bce1e5ab65871fcd3c4064f68d
sonar.token=sqp_cfe62e55125ae2bce1e5ab65871fcd3c4064f68d

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3

# Path to the coverage XML report required by SonarQube
sonar.python.coverage.reportPaths=coverage.xml